name: Generate RSS Feed

on:
  schedule:
    - cron: '10 1 * * *' # 日本時間10:10に実行（UTC 01:10）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch JSON data
        run: |
          curl -s "https://kosodate-green.mlit.go.jp/assets/data/news.json" -o news.json

      - name: Process JSON and Generate RSS
        run: |
          mkdir -p public
          echo '<?xml version="1.0" encoding="UTF-8"?>' > public/rss.xml
          echo '<rss version="2.0">' >> public/rss.xml
          echo '<channel>' >> public/rss.xml
          echo '<title>子育てグリーン住宅支援事業 RSS</title>' >> public/rss.xml
          echo '<link>https://kosodate-green.mlit.go.jp/</link>' >> public/rss.xml
          echo '<description>子育てグリーン住宅支援事業の最新情報</description>' >> public/rss.xml
          
          now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          fourteen_days_ago=$(date -u -d "-14 days" +"%Y-%m-%d")
          
          cat news.json | jq -r --arg now "$now" --arg cutoff "$fourteen_days_ago" '.list[] | select(.date >= $cutoff) | "<item><title>" + .title + "</title><link>" + .url + "</link><guid isPermaLink=\"true\">" + .url + "</guid><pubDate>" + .date + "</pubDate></item>"' >> public/rss.xml
          
          echo '</channel>' >> public/rss.xml
          echo '</rss>' >> public/rss.xml

      - name: Create .nojekyll file
        run: |
          touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
