name: Generate RSS Feed

on:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Generate RSS
        run: |
          set -eux

          mkdir -p docs

          if [ -f docs/rss.xml ]; then
            mv docs/rss.xml docs/rss_old.xml
          fi

          # JSON を取得
          curl -s https://kosodate-green.mlit.go.jp/assets/data/news.json -o news.json

          NOW=$(date +%s)
          # 過去5日間 = 5日 * 86400秒
          FIVE_DAYS_AGO=$(( NOW - 432000 ))

          : > items.rss

          length=$(jq '.list | length' news.json)

          for i in $(seq 0 $((length - 1))); do
            item=$(jq -r ".list[$i]" news.json)
            title=$(echo "$item" | jq -r '.title')
            url=$(echo "$item"   | jq -r '.url')
            date_str=$(echo "$item" | jq -r '.date')
            id=$(echo "$item"    | jq -r '.id')

            # 日付フォーマットの変換
            date_fmt=$(echo "$date_str" | sed 's/\//-/g')
            epoch=$(date -d "$date_fmt" +%s)

            # 過去5日以内なら出力
            if [ $epoch -ge $FIVE_DAYS_AGO ]; then
              pub_date=$(date -R -d "$date_fmt")
              cat <<EOF >> items.rss
<item>
  <title>${title}</title>
  <link>${url}</link>
  <guid isPermaLink="false">${id}</guid>
  <pubDate>${pub_date}</pubDate>
</item>
EOF
            fi
          done

          cat <<EOF > docs/rss.xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
  <title>子育てグリーン住宅支援事業 最新情報</title>
  <link>https://your-github-pages-url.example</link>
  <description>子育てグリーン住宅支援事業の新着情報をRSSフィードで提供</description>
  <lastBuildDate>$(date -R)</lastBuildDate>
  <pubDate>$(date -R)</pubDate>
  <ttl>1800</ttl>
$(cat items.rss)
</channel>
</rss>
EOF

          # 変更の有無にかかわらず、rss.xml を生成（差分チェックは任意）
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/rss.xml
          git commit -m "Update RSS feed"
          git push origin main

      - name: Upload rss.xml artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: rss.xml
          path: docs/rss.xml
