name: Generate RSS Feed

on:
  schedule:
    - cron: '10 1 * * *' # 日本時間10:10に実行（UTC 01:10）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch JSON data
        run: |
          curl -s "https://kosodate-green.mlit.go.jp/assets/data/news.json" -o news.json

      - name: Process JSON and Generate RSS
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > rss.xml
          echo '<rss version="2.0">' >> rss.xml
          echo '<channel>' >> rss.xml
          echo '<title>子育てグリーン住宅支援事業 RSS</title>' >> rss.xml
          echo '<link>https://kosodate-green.mlit.go.jp/</link>' >> rss.xml
          echo '<description>子育てグリーン住宅支援事業の最新情報</description>' >> rss.xml
          
          now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          fourteen_days_ago=$(date -u -d "-14 days" +"%Y-%m-%d")
          
          cat news.json | jq -r --arg now "$now" --arg cutoff "$fourteen_days_ago" '.list[] | select(.date >= $cutoff) | "<item><title>" + .title + "</title><link>" + .url + "</link><guid isPermaLink=\"true\">" + .url + "</guid><pubDate>" + .date + "</pubDate></item>"' >> rss.xml
          
          echo '</channel>' >> rss.xml
          echo '</rss>' >> rss.xml

      - name: Create .nojekyll file
        run: |
          touch .nojekyll

      - name: Check for changes
        run: |
          git diff --quiet || echo "Changes detected"

      - name: Commit and Push if changes exist
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add rss.xml .nojekyll
          git commit -m "Update RSS feed" || exit 0
          git push origin main
