name: Generate RSS Feed

on:
  schedule:
    - cron: '10 1 * * *'  # 日本時間 10:10 (UTC 1:10)
  workflow_dispatch:  # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch JSON and Convert to RSS
        run: |
          # 最新の JSON を取得
          curl -sL "https://kosodate-green.mlit.go.jp/assets/data/news.json" -o news.json

          # RSS フィードのヘッダーを作成
          echo '<?xml version="1.0" encoding="UTF-8"?>' > rss.xml
          echo '<rss version="2.0">' >> rss.xml
          echo '<channel>' >> rss.xml
          echo '  <title>子育てグリーン住宅支援事業 新着情報</title>' >> rss.xml
          echo '  <link>https://kosodate-green.mlit.go.jp/</link>' >> rss.xml
          echo '  <description>最新のニュースを提供します</description>' >> rss.xml
          echo '  <language>ja</language>' >> rss.xml
          
          # JSON から各ニュース記事を RSS アイテムとして追加
          jq -c '.[]' news.json | while read item; do
            title=$(echo $item | jq -r '.title')
            link=$(echo $item | jq -r '.url')
            pubDate=$(echo $item | jq -r '.date' | xargs -I {} date -d {} -R) # RFC 2822 形式
            guid=$(echo $link | md5sum | awk '{print $1}') # URL の MD5 ハッシュで一意の ID を生成

            echo '  <item>' >> rss.xml
            echo "    <title>${title}</title>" >> rss.xml
            echo "    <link>${link}</link>" >> rss.xml
            echo "    <guid isPermaLink=\"false\">${guid}</guid>" >> rss.xml
            echo "    <pubDate>${pubDate}</pubDate>" >> rss.xml
            echo '  </item>' >> rss.xml
          done

          echo '</channel>' >> rss.xml
          echo '</rss>' >> rss.xml

      - name: Commit and Push RSS Feed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add rss.xml .nojekyll
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push origin main
